[build]
  base = "/"
  publish = "frontend"
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://inventario-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
